<?php

namespace CE\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditRepository extends EntityRepository
{
    public function findAllWeekAudits(\DateTime $date, User $user, Category $category)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT a, u, c FROM CETestBundle:Audit JOIN a.user u JOIN a.category c WHERE u.id = :id AND a.date BETWEEN :start AND :end AND c.id = :category')
            ->setParameters(array(
                'id' => $user->getId(),
                'start' => $date,
                'end' => $date->add(new \DateInterval("P7D")),
                'category' => $category->getId()
            ));
        return $query->getResult();
    }
}
